import os
import subprocess
import ollama
import pdfplumber
import sys
import re

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from Prompts.slides_latex_prompt import SLIDES_LATEX_PROMPT

class LatexAgent:

    def __init__(self, model_name="qwen3-vl"):
        self.model_name = model_name

    def run(self, input_pdf_path, output_filename, max_attempts=2):
        output_dir = "Data/intermediate"
        os.makedirs(output_dir, exist_ok=True)
        
        tex_path = os.path.join(output_dir, f"{output_filename}.tex")

        print(f"Extracting text from slide PDF: {input_pdf_path}")
        
        chunks, total_slides = self._extract_and_chunk_pdf(input_pdf_path, chunk_size=4)
        print(f"Total slides found: {total_slides}. Broken into {len(chunks)} chunks for safe processing.")
        
        attempt = 0
        while attempt < max_attempts:
            print(f"\nAttempt {attempt + 1} of {max_attempts}")
            all_latex_frames = []
            
            for i, chunk in enumerate(chunks):
                slide_count = chunk.count("--- SLIDE")
                print(f"Generating Beamer frames for batch {i+1}/{len(chunks)} (up to {slide_count} slides) via {self.model_name}...")
                
                try:
                    response = ollama.chat(
                        model=self.model_name,
                        messages=[
                            {
                                "role": "system", 
                                "content": SLIDES_LATEX_PROMPT
                            },
                            {"role": "user", "content": f"SLIDE TEXT CHUNK:\n{chunk}"}
                        ],
                        options={"num_predict": 8192}
                    )
                    raw_output = response["message"]["content"].strip()
                    clean_frames = self._clean_frames_output(raw_output)
                    all_latex_frames.append(clean_frames)
                except Exception as e:
                    print(f"Error generating batch {i+1}: {e}. Skipping this chunk.")
            
            print("Assembling all chunks into final LaTeX document...")
            latex_code = self._assemble_full_document(all_latex_frames)

            with open(tex_path, "w", encoding="utf-8") as f:
                f.write(latex_code)

            pdf_path = self._compile_to_pdf(tex_path, output_dir, output_filename)
            
            if pdf_path:
                print("Agent completed successfully.")
                return pdf_path
            
            attempt += 1
            if attempt < max_attempts:
                print("Retrying LaTeX generation due to compilation failure...\n")

        print("Agent failed after multiple attempts.")
        return None

    def _extract_and_chunk_pdf(self, pdf_path, chunk_size=4):
        chunks = []
        current_chunk = []
        total_pages = 0
        
        with pdfplumber.open(pdf_path) as pdf:
            total_pages = len(pdf.pages)
            for i, page in enumerate(pdf.pages):
                text = page.extract_text()
                if text:
                    current_chunk.append(f"--- SLIDE {i+1} ---\n{text}")
                
                if (i + 1) % chunk_size == 0:
                    chunks.append("\n".join(current_chunk))
                    current_chunk = []
            
            if current_chunk:
                chunks.append("\n".join(current_chunk))
                
        return chunks, total_pages

    def _clean_frames_output(self, text):
        backticks = "`" * 3
        text = re.sub(rf"{backticks}(?:latex)?", "", text)
        text = text.replace(backticks, "")
        text = text.strip()
        
        begin_count = text.count(r"\begin{frame}")
        end_count = text.count(r"\end{frame}")
        
        if begin_count > end_count:
            missing = begin_count - end_count
            text += "\n\\end{frame}" * missing
            
        return text

    def _assemble_full_document(self, frames_list):
        combined_frames = "\n\n".join(frames_list)
        
        document = r'''\documentclass{beamer}

\title{Talexa Lecture Series}
\author{Generated by Talexa}
\date{\today}

\begin{document}

\begin{frame}
    \titlepage
\end{frame}

''' + combined_frames + r'''

\end{document}
'''
        return document

    def _compile_to_pdf(self, tex_path, output_dir, output_name):
        print(f"Compiling {output_name}.pdf...")
        pdf_path = os.path.join(output_dir, f"{output_name}.pdf")
        
        try:
            for i in range(2):
                result = subprocess.run(
                    ["pdflatex", "-interaction=nonstopmode", f"-output-directory={output_dir}", tex_path],
                    capture_output=True, 
                    text=True,
                    encoding="utf-8",
                    errors="replace"
                )
            
            if os.path.exists(pdf_path):
                print(f"Success! View result: {pdf_path}")
                if result.returncode != 0:
                    print("Note: LaTeX finished with minor warnings, but the PDF was generated successfully.")
                return pdf_path
            else:
                print(f"PDF Compilation completely failed for {output_name}.")
                print("--- LaTeX Error Tail ---")
                if result.stdout:
                    print("\n".join(result.stdout.splitlines()[-15:]))
                return None
                
        except Exception as e:
            print(f"Execution Error: {e}")
            return None

if __name__ == "__main__":
    input_file = "Data/input/slides.pdf" 
    if os.path.exists(input_file):
        agent = LatexAgent()
        agent.run(input_file, "Lecture_Slides_Talexa")
    else:
        print(f"Input file not found at: {input_file}")
